export const paths = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  COURSE: "/course",
  LATEST: "/latest/:post",
  CREATOR: "/creator",
  SEARCH: "/search/:post",
  QUIZ: "/quiz",
  REVIEW: "/review",
  PROFILE: "/profile",
  GIFT: "/gift",
  DONOR: "/donor",
  ADMIN: "/admin",
  NOTFOUND: "/404",
};
